blank_issues_enabled: false---
name: New Compatibility Patch
about: List a mod needing a fix for its items.
title: ''
labels: kind/new-compat status/wip
assignees: ''
---

### Description
Fixes [mod name] inventory items breaking mine detectors.
Closes #Issue Number

### Changes
**Compat - Main**
- Changes made to `STAX`

**Compat - [Mod Prefix/Name]**
- Simple patch applied to:
  - `item_className`
- Other changes to classes.

**Tools**
- Changes made to non-addon related files.