name = "Starsim ACEX Compat"
author = "CAnnon"
prefix = "STAX"
mainprefix = "z"

[version]
path = "addons/Main/script_version.hpp"
git_hash = 0

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "LICENSE",
    "README.md"
]
exclude = [
    "*.psd"
]

[properties]
author = "Cannon"